services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    container_name: api
    ports:
      - '3010:3010'
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    container_name: app
    ports:
      - '5173:80'
    env_file:
      - .env
    depends_on:
      - api

  docs:
    build:
      context: .
      dockerfile: containers/docs/Dockerfile
    container_name: docs
    ports:
      - '8080:80'
    volumes:
      - ./docs:/docs


volumes:
  postgres_data:

